### ISSUE TITLE
pip install broken?

### ISSUE THREAD

**Issue by ripxorip** [pwitab/visma#7]
`pip install visma
Downloading/unpacking visma
  Downloading visma-0.0.3-py3-none-any.whl
Installing collected packages: visma
*** Error compiling '/tmp/pip-build-5qqko9q1/visma/visma/api.py'...
  File "/tmp/pip-build-5qqko9q1/visma/visma/api.py", line 52
    f'GET :: HTTP:{r.status_code}, {r.content}')
                                              ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip-build-5qqko9q1/visma/visma/base.py'...
  File "/tmp/pip-build-5qqko9q1/visma/visma/base.py", line 140
    f'{self.__class__.__name__} :: {field_name} '
                                                ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip-build-5qqko9q1/visma/visma/cli.py'...
  File "/tmp/pip-build-5qqko9q1/visma/visma/cli.py", line 22
    __browser.open((f'https://identity.vismaonline.com/connect/authorize'
                                                                        ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip-build-5qqko9q1/visma/visma/manager.py'...
  File "/tmp/pip-build-5qqko9q1/visma/visma/manager.py", line 32
    f'{method} is not an allowed method on this '
                                                ^
SyntaxError: invalid syntax`

Seen with both with python2 and python3, am I missing something?

**Comment by Krolken** [comment]
seems it is complaining about f-strings. That is not available in anything under 3.6. 
I will make it clearer in the docs that you need python 3.6 or higher to be able to use the library.
Could you try to install in a 3.6 environment to see if this resolves the issue?

**Comment by ripxorip** [comment]
Thanks for the reply, yes we are actually on python 3.5 so that explains it. Not sure that I can easily install 3.6 on my server though. I will check that and get back to you.
